### ISSUE TITLE
Storybook is struggling

### ISSUE THREAD

**Issue by with-heart** [Soil-labs/eden-app-2-FrontEnd#739]
I think there's something wrong with our Storybook setup where it's not hot reloading correctly sometimes. I have to manually refresh the page often to get the output to appear, which I've never had to do in other Storybook setups.

Not a high priority but it's frustrating enough that I'll try to track down the cause at some point

**Comment by e-roy** [comment]
this might be within the mock data, mock functions are run every page reload, so if there are any functions that are intensive, this my weight down local machine.  

there have been changes to the mock data lately, so please make sure you are synced up to the latest.

are you experiencing this on which side of this PR #716 ?  before this or after this?

**Comment by with-heart** [comment]
It's been doing it since I started getting involved again. I don't think there's anything in the mocks that would cause that kind of performance drop, they'd have to be unreasonably large objects
