### ISSUE TITLE
Use `msw` for mocking our APIs

### ISSUE THREAD

**Issue by with-heart** [Soil-labs/eden-app-2-FrontEnd#776]
[`msw` (**m**ock **s**ervice **w**orkers)](https://mswjs.io/) is a next-gen api mocking library.

> Mock by intercepting requests on the network level. Seamlessly reuse the same mock definition for testing, development, and debugging.

At a high level, this means that we can define a single mock server that we can then use for `yarn dev`, `yarn test`, and `yarn storybook`.

Here are some of the benefits of using `msw` over individual use site mocks (what we're currently doing):

- mock once, use everywhere
- mock data is accessed the same way it is in prod: via network calls
- mocks grow *as a system* with our app rather than being a bunch of one-off objects scattered about
- since it's a mock _server_, we can add logic and behavior to the endpoints in order to make it act like a real backend

Overall, this means we can get a lot more bang for a buck while investing significantly less time into mocking.

**Comment by e-roy** [comment]
can the current mocks that have been created and grown [here](https://github.com/Soil-labs/eden-app-2-FrontEnd/tree/develop/packages/mock/src) be used with in `msw`?  

These have been built as mocks to represent a query from the api that are being loaded from objects that are type safe with the  backend api.  the files in `typeMocks` folder are being used across multiple files in the `graphqlMocks` folder

are these what you are considering to be individual use site mocks?  or are you considering these mocks in the [alpha app](https://github.com/Soil-labs/eden-app-2-FrontEnd/tree/develop/apps/alpha/utils/mock) to be this?  

or both?

**Comment by with-heart** [comment]
@e-roy Yeah we can use any source of data we want. `msw` is totally agnostic to where the data comes from, it's just concerned with setting up the service workers.

#777 is more relevant to discussing _how_ to mock our data

**Comment by e-roy** [comment]
@with-heart agree on all of this.  I'm noticing a lot of bad mocks scattered inside component level, storybook and test files, a better global system would be good.  can this be built into the current `@eden/package-mock` package?

**Comment by e-roy** [comment]
Is there an advantage for `msw` over the `import { MockedProvider } from "@apollo/client/testing";` ?

seems like the `MockedProvider` for apollo does a lot of the same things?  I created a test in PR #792
